### ISSUE TITLE
Can't teleport through open door

### ISSUE THREAD

**Issue by sambuev** [mitchemmc/VRContentExamples#10]
Hello, I have started to test your contentexamples, I like it very much. I have created simple level with your doors, when I opening door, teleport can't see through this door and to fix it I have to move my hand toward to door and cross the door line and only then teleport working again.
Is it possible to teleport easily when door is already open?

P.S. Also how to make door stop rotation if it hits my head, I was thinking to add sphere-collide to mycharacter, but it still ignores it. 

Thank you!

**Comment by mitchemmc** [comment]
That's odd, I'll have a look this weekend and see if I can reproduce the issue

**Comment by mitchemmc** [comment]
I wasn't able to reproduce your issue of not being able to teleport through the door, make sure you check the collision in your level.
As far as stopping the door, currently it isn't supported because the door doesn't use UE4's physics system and instead simulates its own physics manually just because I found this led to more predictable behaviour, if you want it to use physics look into UE4s physics constraints
