### ISSUE TITLE
4.16 - errors while running.

### ISSUE THREAD

**Issue by sambuev** [mitchemmc/VRContentExamples#12]
Hello, please don't delete this message. 
I have some errors while I running Word Interaction map and there is few physics spheres **1.A** they are producing some errors 

Warning Constraint in '/Game/Maps/UEDPIE_0_VR_WI_02.VR_WI_02:PersistentLevel.BP_InteractiveStaticMeshActorConstraint5.PhysicsConstraint' attempting to create a joint between objects that are both static.  No joint created.

Can you please review what is the problem?

Thank you.

**Comment by mitchemmc** [comment]
If it's what I think it is it doesn't actually effect things, it's just a warning from a bug in the engine https://answers.unrealengine.com/questions/470900/add-physics-constraint-component-node-causes-a-war.html it was fixed in 4.15 https://issues.unrealengine.com/issue/UE-36089 but they must have broke it again in 4.16, again shouldn't effect things but feel free to create comment on the answer hub telling them about it

**Comment by mitchemmc** [comment]
Actually looking at it again this error is different, are you sure that both your objects (the one you're grabbing with and the one you're grabbing) are set to moveable?

**Comment by sambuev** [comment]
I just open and run your map, I did not change anything, while I stop playing in the editor, it shows me Errors while playing. I just reported it here. 
I use HTC Vive on Windows 10 and UE 4.16.1

**Comment by mitchemmc** [comment]
Finally got some free time and it is the bug I linked in first response, unfortunately it is up to Epic to fix. It won't effect any game play things however.
